openapi: 3.1.0
info:
  version: v1
  title: vehicle-profile API
  description: vehicle-profile RESTFul api for openapi 3.1
  termsOfService: 'https://jumkid.com/terms-of-use'
  contact:
    name: support
    url: jumkid.com
    email: support@jumkid.com
  license:
    name: Jumkid Public License
    url: 'http://license.jumkid.com'

servers:
  - description: Testing
    url: 'http://test.jumkid.com'
  - description: Live production
    url: 'http://api.jumkid.com'

tags:
  - name: v1
    description: API for version 0.9.1
  - name: test
    description: API for test

paths:
  '/vehicle':
    get:
      tags: [ 'v1' ]
      operationId: getVehicles
      description: get all vehicles by user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        '403':
          description: FORBIDDEN
          content:
            application/json:
              schema:
                items:
                  $ref: 'https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/CustomErrorResponse'

    post:
      tags: [ 'v1' ]
      operationId: addVehicle
      description: add new activity for user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '403':
          description: FORBIDDEN
          content:
            application/json:
              schema:
                items:
                  $ref: 'https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/CustomErrorResponse'

  '/vehicle/{vehicleId}':
    get:
      tags: [ 'v1' ]
      operationId: get single vehicle
      description: get single private vehicle profile with corresponding user id or public vehicle profile
      parameters:
        - name: vehicleId
          description: vehicle identifier
          in: path
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '403':
          description: FORBIDDEN
          content:
            application/json:
              schema:
                items:
                  $ref: 'https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/CustomErrorResponse'    
        '404'
          description: NOT_FOUND
          
    post:
      tags: [ 'v1' ]
      operationId: addVehicle
      description: add new activity for user
      parameters:
        - name: vehicleId
          description: vehicle identifier
          in: path
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vehicle'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '403':
          description: FORBIDDEN
          content:
            application/json:
              schema:
                items:
                  $ref: 'https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/CustomErrorResponse'
        '409':
          description: CONFLICT
          content:
            application/json:
              schema:
                items:
                  $ref: 'https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/CustomErrorResponse'

    delete:
      tags: [ 'v1' ]
      operationId: deleteVehicle
      description: delete an existing vehicle for user
      parameters:
        - name: vehicleId
          description: vehicle identifier
          in: path
          required: true
      responses:
        '204':
          description: NOT_FOUND
        '403':
          description: FORBIDDEN
          content:
            application/json:
              schema:
                items:
                  $ref: 'https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/CustomErrorResponse'
    
  '/vehicle/import':
    post:
      tags:
        - v1
      operationId: import
      description: import vehicle data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                tags:
                  type: array
                  format: string
      responses:
        '200':
          description: import vehicle data in csv format
          content:
            application/json:
              schema:
                type: integer
                
components:
  schemas:
    Vehicle:
      description: Model of vehicle
      properties:
        vehicleId:
          type: string
        name:
          type: string
        make:
          type: string
        model:
          type: string
        modelYear:
          type: integer
        trimLevel:
          type: string
        accessScope:
          $ref: '#/components/schemas/AccessScope'
        vehicleEngine:
          $ref: '#/components/schemas/VehicleEngine'
        vehicleTransmission:
          $ref: '#/components/schemas/VehicleTransmission'
        createdBy:
          type: string
        creationDate:
          $ref: 'https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/LocalDateTime'
        modifiedBy:
          type: string
        modificationDate:
          $ref: 'https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/LocalDateTime'

    VehicleEngine:
      description: Model of vehicle engine
      properties:
        vehicleEngineId:
          type: integer
        name:
          type: string
        type:
          type: string
        cylinder:
          type: integer
        fuelType:
          type: string
        horsepower:
          type: integer
        torque:
          type: integer
        manufacturerEngineCode:
          type: string

    VehicleTransmission:
      description: Model of vehicle transmission
      properties:
        vehicleTransmissionId:
          type: integer
        name:
          type: string
        type:
          type: string
        availability:
          type: string
        automaticType:
          type: string
        numberOfSpeeds:
          type: integer

    AccessScope:
      type: string
      enum: [ public, private ]